### ISSUE TITLE
Il divieto al linguaggio blasfemo e' fuoriluogo

### ISSUE THREAD

**Issue by peoro** [pythonitalia/code-of-conducts#6]
Il commit 5dbe46de73004e66a13602a7b15b6e7c82a4a80f ha introdotto il divieto ufficiale alla blasfemia.
In precedenza ho personalmente assistito a ban privi di avvertimenti come conseguenza a bestemmie sulle chat di Python Italia.

Ritengo che questo divieto sia fuoriluogo in una community simile, per svariate ragioni.

La blasfemia non e' un crimine d'odio, ne' un comportamento discriminatorio, ne' un atto condannato dalla stragrande maggioranza delle persone.
Spero che chiunque in questa community sia favorevole a vietare la discriminazione religiosa (cosi' come quella raziale, di identita' di genere, di orientamento sessuale etc), ma le blasfemie non sono discriminazione, ne' implicano questa.
Allo stesso modo comportamenti troppo offensivi o violenti non dovrebbero essere tollerati, ma non ritengo corretto un accanimento specifico verso la blasfemia.

Un divieto alle blasfemie e' un divieto ad un qualcosa di arbitrario, che irrita alcune persone cosi' come altre vengono irritate da insulti verso i loro software o sistemi operativi preferiti, verso il partito o le figure politiche in cui credono, o addirittura da semplici parolacce o riferimenti sessuali.
La religione e' un argomento completamente indipendente da Python e Python Italia, e reputo fuori luogo un divieto specifico per la blasfemia.

Credo di aver assistito alla discussione che ha causato l'aggiunta di questa regola: pochi giorni fa sulla chat @PythonIta su Telegram. Da cio' che ho visto, un paio di moderatori del gruppo si sono espressi contrari alla blasfemia mentre la maggioranza della chat scherzava sulla questione.
Credo che l'intera community dovrebbe avere la possibilita' di esprimersi a riguardo.

Data la natura dell'argomento, mi sorge spontaneo ipotizzare che qualche persona ai vertici di Python Italia sia fortemente religiosa e che per questo si senta personalmente interessata.
Se questo fosse il caso, reputerei che la questione sia stata approcciata in maniera sbagliata e scorretta, da una comunita' basata attorno ad un software Open Source, che dovrebbe dare massimo peso alla trasparenza.

**Comment by patrick91** [comment]
ciao @peoro, scusa per il ritardo nella risposta, avrei voluto rispondere subito dopo i chiarimenti sul gruppo Telegram. Posso capire le motivazioni che ti hanno spinto ad aprire questa issue, però ecco, il gruppo è relativo a Python, non è il luogo adatto per OT e bestemmie (per quanto possano essere tollerati).

Il cambiamento sulla CoC è stato fatto perché purtroppo ci sono state lamentele sul fatto che alcuni punti non sono super espliciti. Se hai idee su come migliorare quel punto sentiti libero di mandare una PR. Intanto chiudo la discussione qui, visto che ne abbiamo parlato in chat.

**Comment by Axeltherabbit** [comment]
Se permetti l'OT c'è di continuo e comprensivo di offese insensate, troll(peoro), flame, inutilità varie e ban rari, però parlare per fare un ritrovo a Pisa tra gli utenti del gruppo è fuoriluogo e poco tollerato.

**Comment by patrick91** [comment]
Ciao @Axeltherabbit! Questo non è il posto migliore per discutere di questo caso in particolare, se vuoi mi puoi scrivere in privato. O ne parliamo sul gruppo anche (non sono super attivo purtroppo).

Comunque non credo abbiamo gestito super bene il presunto OT sul ritrovo a Pisa, mi scuso personalmente per questo, è capitato in un momento di confusione se non ho visto male :)

Ti chiedo di avere un po' di pazienza e comprensione, tutti gli admin hanno un lavoro a tempo pieno (e/o studiano) quindi non è sempre facile gestire il gruppo, gli errori capitano ;)

**Comment by meloncello** [comment]
secondo me aveva ragione il peoro, riaprite pure la issue

**Comment by meloncello** [comment]
@axeltherabbit puppa
