### ISSUE TITLE
troll & lamer

### ISSUE THREAD

**Issue by gionniboy** [pythonitalia/code-of-conducts#9]
> **premessa**: questa issue non vuole minare il diritto all'inclusività, bensì trovare un equilibrio per evitare discussioni senza senso che potrebbero inasprire la community o i partecipanti alla community, soprattutto online, con discorsi vuoti, ignoranti e fine a se stessi che porterebbero alla perdita di altri componenti della community [minando cosi invece quel diritto all'inclusività citato prima].
> Ovvero: proviamo a rendere la community un posto migliore per tutti evitando atteggiamenti blasfemi, ma anche poco costruittivi. Anzi distruttivi in generale.

Salve,
secondo me c'è un bug molto grosso nel COC attuale.
Non c'è una gestione/limitazione a troll/lamer/scriptkiddy/know-it-all e atteggiamenti connessi.

Esempio classico: 
Parlare di qualcosa che non si conosce, spesso con tono saccente magari, portando le discussioni ad un livello più basso del ridicolo e che poco servono alla community.

Strumenti di attacco più utilizzati: 

- frasi senza logica ne fondamento
- i primi due risultati su google [senza neanche averli letti, spesso] a supporto della propria ipotesi [spacciata spesso per tesi]
- concetti stravolti perchè "il nome fa pensare..." o "pensavo che..."
- aggiungere fuoco alla discussione usando buzzword di cui non si conosce completamente il significato per spostare l'attenzione verso un altro concetto senza senso [prolungando cosi le discussioni senza senso, appunto]

Non sarebbe bello pensare ad un modo per arginare e/o limitare e/o gestire questo tipo di comportamenti?

Ad esempio: 

Un sistema RTFM.
Assicurarsi i fondamentali prima di permettere discussioni più "alte" 
[che non vuol dire: possono parlare/entrare solo quelli skillati, ma significa informarsi prima di parlare per evitare discussioni infinite inutili basate sul nulla - il vecchio RTFM first, ASK later]
[esempio: come fai a chiedere "come ottimizzare una request" se neanche sai cosa è/come è fatta una request?,  oppure consigli su MVC se neanche sai cosa è un frontend o un backend??? e cosi via....]

Attuabile come?
Bastano due/tre domande da parte di un admin per capire se qualcuno sta sparando a caso senza aver cercato documentazione [e quindi di fatto sta inneggiando al flame/trolling].

Come in passato alcune regole del COC hanno aiutato/contribuito a mantenere più clean&lean la community tagliando al nascere certi atteggiamenti allo stesso modo questa regola potrebbe portare più responsabilità verso tutti i componenti della community, soprattutto i più nuovi/giovani/unskilled .

Obiettivi
Evitare che persone, anche educate e rispettose, possano portare la discussioni continuamente a livelli ridicoli fino allo sfinimento senza avere uno strumento nel COC che permetta la community di filtrare o gestire o limitare i suddetti comportamenti.

**Comment by gbonfiglio** [comment]
Non capisco. Uno dei troll piu' famosi di internet che da lezioni di anti trolling? Suona come un suicidio? Poi come fai?

**Comment by meloncello** [comment]
+1

**Comment by gionniboy** [comment]
semplicemente ci tengo alla python community italiana.

**Comment by meloncello** [comment]
io aggiungerei anche il libero uso delle bestemmie/blasfemie se esse riguardassero giochi di parole fatti con nomi di database buffi e palindromi

**Comment by tapionx** [comment]
+1

**Comment by mmat11** [comment]
COCK*

**Comment by patrick91** [comment]
Ciao @gionniboy, non mi sembra molto fattibile quello che stai proponendo per un paio di motivi, gli admin di Python Italia sono *tutti* volontari, nessuno è pagato per controllare ogni minima discussione, cercare di moderare tutti i messaggi è improponibile.

Basterebbe un po' di maturità per evitare questi problemi, però ecco, qui stiamo ancora a chiedere la possibilità di bestemmiare in chat. Per carità sono il primo a chiedere la libertà di parola, ma a volte delle regole sono fondamentali per avere delle community accoglienti. Spero sia chiaro, tutti gli admin sono admin perché hanno dato una mano in vari modi alla community Python italiana e vogliono rendere la community un posto migliore. 

Anni fa quando entrai sul canale Python su IRC non sono stato accolto da bestemmie, parolacce o prese per il sedere, fosse stato così probabilmente non avrei mai continuato ad usare Python. Sono entrato a contatto con delle persone che poi nel tempo sono diventate miei amici. Vorrei che la community Python Italia continui ad essere così, ed immagino questa sia l'idea anche degli altri admin.

Da una parte, personalmente, sono tentato di rendere non ufficiale il canale telegram così da "evitare" tutti questi problemi, credimi, non è facile gestire un canale così grande (e io già non lo sto seguendo molto). Però come dicevo su, vorrei che un nuovo pythonista si senta sempre benvenuto in questa community, sia che entri su IRC, Facebook, Telegram, etc. 

Detto ciò la CoC (sì, si scrive così) non si cambia.

**Comment by gionniboy** [comment]
ciao @patrick91 grazie per aver sbloccato la discussione dandomi possibilità di replica [fino a 8 ore fa negata in modo coatto].

Innanzitutto non capisco perchè mi rispondi parlando di "bestemmie" visto che la mia issue non tocca quel problema. Forse ti stai confondendo con altre issue? Magari il caso di far fare review a qualcuno più attento e pratico? La mia è solo una proposta, anche questa. Nulla di personale.

Riguardo l'impossibilità perché "siamo tutti volontari":
infatti io proponevo una linea di condotta aggiuntiva, cosi come per le bestemmie e per il resto.
O per le regole fin'ora decise avete i cecchini h24  sempre pronti a vigilare?
Oppure nel caso di un problema applicate a posteriori i provvedimenti?

Quindi una linea di condotta non mira a censurare [con gli shooter piazzati sulle vedette] bensì funge da punto di riferimento su "come comportarsi" a chi si avvicina alla community, o per chi ne fa già parte.
E che male c'è nel dire, a chiunque si avvicini alla community, che ai fini di una maggiore cooperazione e ai fini di un livello meno ridicolo delle discussioni "gli utenti sono pregati di RTFM prima di fare domande ridicole" ? E che atteggiamenti ripetuti di ignoranza becera immotivata [vedi esempi nella issue] saranno moderati per evitare triggering&trolling&flaming?

Capisco il tuo punto: ma allora NESSUNA regola andrebbe definita se partiamo dall'assunto "siamo volontari, mica siamo sempre qui a vigilare". Non vedi il controsenso? La forzatura?

Senza considerare che sono rimasto molto dispiaciuto per la chiusura di dialogo: non mi aspettavo certi atteggiamenti [che io reputo fascisti] all'interno di una community OPENSOURCE [free as in speech - do you know?]. Soprattutto essendomi posto in maniera educata e non aggressiva, dettagliando anche tecnicamente la mia issue, facendo esempi concreti, usando il mio account personale e non un fake account e simili. [aka: l'avrei buttata da subito in caciara se le mie intenzioni non fossero state costruttive].

Quando mi parli di telegram: li non so a cosa ti riferisci in quanto sono stato bannato due volte dal gruppo python telegram [la prima volta con motivazioni anche giuste, se consideriamo il CoC, la seconda volta... ancora non è chiaro il motivo del ban (ti prego di guardare i log nel caso in cui avessi dubbi). E mi aveva sbannato uno degli organizzatori. Ma vabbè. Forse è il caso che vi chiariate un poco anche  "internamente" per decidere meglio una politica comune da adottare].

Mi dispiace molto che la issue, con intenzioni costruttive, si sia trasformata nell'ennesimo teatrino: forse magari dovremmo avere atteggiamenti più morbidi e aperti verso la community che non fa parte del "core team" ?

Per concludere dici "vorrei che qualsiasi nuovo pythonista si sentisse a suo agio".
Mi posso permettere di dire che, da nuovo pythonista che si affaccia alla community del suo paese, non mi sono sentito per niente a mio agio? Anzi, al contrario, il disagio provato è stato incalcolabile.

Infine "Detto ciò la CoC non si cambia.": hai provato a guardare questa frase dall'esterno?
"il coc non si cambia per i motivi sopra esposti" e "il coc non si cambia." sono due frasi diverse. 
Con peso diverso. 
La tua sembra urlare e sottolineare: è inutile che aprite ancora issue sul CoC ... tanto lo decidiamo "noi" come e quando si cambia.

Permettimi di dire che questo atteggiamento è molto poco opensource e ancora meno "Free".
[Stallman disapproved.]

My two satoshis.

Gionni

**Comment by meloncello** [comment]
@gionniboy è inutile continuare a scrivere wall of text, tanto tra poco Patrick ti ri-blocca la issue.

**Comment by patrick91** [comment]
> ciao @patrick91 grazie per aver sbloccato la discussione dandomi possibilità di replica [fino a 8 ore fa negata in modo coatto].

Chiedo scusa per aver chiuso la discussione, è stato un errore.

> Innanzitutto non capisco perchè mi rispondi parlando di "bestemmie" visto che la mia issue non tocca quel problema. Forse ti stai confondendo con altre issue? Magari il caso di far fare review a qualcuno più attento e pratico? La mia è solo una proposta, anche questa. Nulla di personale.

Mi sono lasciato distrarre dai commenti alla issue, oltre che dalle varie richieste in chat di rimuovere quel ban, chiedo venia.
 
> Riguardo l'impossibilità perché "siamo tutti volontari":
> infatti io proponevo una linea di condotta aggiuntiva, cosi come per le bestemmie e per il resto.
> O per le regole fin'ora decise avete i cecchini h24 sempre pronti a vigilare?
> Oppure nel caso di un problema applicate a posteriori i provvedimenti?
> 
> Quindi una linea di condotta non mira a censurare [con gli shooter piazzati sulle vedette] bensì funge da punto di riferimento su "come comportarsi" a chi si avvicina alla community, o per chi ne fa già parte.
> E che male c'è nel dire, a chiunque si avvicini alla community, che ai fini di una maggiore cooperazione e ai fini di un livello meno ridicolo delle discussioni "gli utenti sono pregati di RTFM prima di fare domande ridicole" ? E che atteggiamenti ripetuti di ignoranza becera immotivata [vedi esempi nella issue] saranno moderati per evitare triggering&trolling&flaming?
> 
> Capisco il tuo punto: ma allora NESSUNA regola andrebbe definita se partiamo dall'assunto "siamo volontari, mica siamo sempre qui a vigilare". Non vedi il controsenso? La forzatura?
> 
> Senza considerare che sono rimasto molto dispiaciuto per la chiusura di dialogo: non mi aspettavo certi atteggiamenti [che io reputo fascisti] all'interno di una community OPENSOURCE [free as in speech - do you know?]. Soprattutto essendomi posto in maniera educata e non aggressiva, dettagliando anche tecnicamente la mia issue, facendo esempi concreti, usando il mio account personale e non un fake account e simili. [aka: l'avrei buttata da subito in caciara se le mie intenzioni non fossero state costruttive].

Ripeto è stato uno sbaglio chiudere la discussione, non era un attacco contro te.

> Quando mi parli di telegram: li non so a cosa ti riferisci in quanto sono stato bannato due volte dal gruppo python telegram [la prima volta con motivazioni anche giuste, se consideriamo il CoC, la seconda volta... ancora non è chiaro il motivo del ban (ti prego di guardare i log nel caso in cui avessi dubbi). E mi aveva sbannato uno degli organizzatori. Ma vabbè. Forse è il caso che vi chiariate un poco anche "internamente" per decidere meglio una politica comune da adottare].
> 
> Mi dispiace molto che la issue, con intenzioni costruttive, si sia trasformata nell'ennesimo teatrino: forse magari dovremmo avere atteggiamenti più morbidi e aperti verso la community che non fa parte del "core team" ?
> 
> Per concludere dici "vorrei che qualsiasi nuovo pythonista si sentisse a suo agio".
> Mi posso permettere di dire che, da nuovo pythonista che si affaccia alla community del suo paese, non mi sono sentito per niente a mio agio? Anzi, al contrario, il disagio provato è stato incalcolabile.

Puoi elaborare un po', ti riferisci a questa issue od altri eventi in particolare? 
Mi spiace la community ti abbia causato del disagio e, di nuovo, chiedo scusa per i miei toni su questa issue, ho sbagliato.

> 
> Infine "Detto ciò la CoC non si cambia.": hai provato a guardare questa frase dall'esterno?
> "il coc non si cambia per i motivi sopra esposti" e "il coc non si cambia." sono due frasi diverse.
> Con peso diverso.
> La tua sembra urlare e sottolineare: è inutile che aprite ancora issue sul CoC ... tanto lo decidiamo "noi" come e quando si cambia.

Avrei dovuto dare una rilettura al mio messaggio, concordo sul tono non corretto.

> 
> Permettimi di dire che questo atteggiamento è molto poco opensource e ancora meno "Free".
> [Stallman disapproved.]
> 
> My two satoshis.

Per quanto riguarda l'argomento principale della issue ne discuto con gli altri e vediamo un po'.

**Comment by YellowPecora** [comment]
venite tutti da me che vi esco il CoCK
